CREATE TABLE USERDEMO([USERID] INT IDENTITY(101,1),[USERNAME] VARCHAR(255),[DEVICEID] INT)

CREATE TABLE MOBILEBRAND([MOBILEBRANDID] INT IDENTITY(101,1),[MOBRANDNAME] VARCHAR(24),[DEVICEID] INT)

CREATE TABLE LAPTOPBRAND([LAPTOPBRANDID] INT IDENTITY(101,1),[LAPTOPBRANDNAME] VARCHAR(24),[DEVICEID] INT)
/*
CREATE TABLE DEVICEDEMO([DEVICEID] INT IDENTITY(101,1),[DEVICETYPE] VARCHAR(25),[MOBILEBRANDID] INT ,[LAPTOPBRANDID] INT)

ALTER TABLE DEVICEDEMO DROP COLUMN MOBILEBRANDID,LAPTOPBRANDID

CREATE TABLE USERACTION([HITID] INT IDENTITY(101,1),[HITTYPE] VARCHAR(22))
DROP TABLE USERACTION
*/
CREATE TABLE DEVICECONNECTION([CONNECTIONID] INT IDENTITY(101,1),[CONNECTIONTYPE] VARCHAR(24))

CREATE TABLE FACEBOOKHITHISTORY([HITHISTORYID] INT IDENTITY(101,1),[HITID] INT,CREATEON DATETIME DEFAULT GETDATE(),[USERID] INT,[DEVICEID] INT,[CONNECTIONID] INT)