USE TASK

CREATE TABLE USER_DATA([USERID] INT IDENTITY(1,1),[USERNAME] VARCHAR(50),
[USEREMAIL] VARCHAR(50),[USERMOBILENO] VARCHAR(50),[USERPASSWORD] VARCHAR(50))
INSERT INTO USER_DATA VALUES('KARAN','SHAHKARAN2312@GMAIL.COM','7990213036','12322322')
INSERT INTO USER_DATA VALUES('AMAN','AMAN@123','99852543356','45566545')
INSERT INTO USER_DATA VALUES('RAJESH','RAJESH@123','564484875','414613')
INSERT INTO USER_DATA VALUES('AKSHAY','AKSHAY@778','4455564','445442')
INSERT INTO USER_DATA VALUES('DIPAK','DIPALK@5546','78889','55555')
INSERT INTO USER_DATA VALUES('SHREYANCHI','SHREYA@252246','8978889','7855555')
SELECT * FROM USER_DATA


CREATE TABLE LOOKUPTYPE([LOOKUPTYPEID] INT IDENTITY(1,1) ,[LOOKUPTYPENAME] VARCHAR(50))
INSERT INTO LOOKUPTYPE VALUES('HITTYPE')
INSERT INTO LOOKUPTYPE VALUES('DEVICETYPE')
INSERT INTO LOOKUPTYPE VALUES('CONNECTIONTYPE')
INSERT INTO LOOKUPTYPE VALUES('AUTHENTICATION')
SELECT * FROM LOOKUPTYPE

CREATE TABLE LOOKUPVALUE([LOOKUPVALUEID] INT IDENTITY(1,1),[LOOKUPVALUENAME] VARCHAR(50),[LOOKUPTYPEID] INT )
INSERT INTO LOOKUPVALUE VALUES('LIKE',1)
INSERT INTO LOOKUPVALUE VALUES('SHARE',2)
INSERT INTO LOOKUPVALUE VALUES('COMMENT',3)
UPDATE LOOKUPVALUE SET LOOKUPTYPEID=1 WHERE LOOKUPVALUEID=2 OR LOOKUPVALUEID=3

INSERT INTO LOOKUPVALUE VALUES('MOBILE',2)
INSERT INTO LOOKUPVALUE VALUES('LAPTOP',2)

INSERT INTO LOOKUPVALUE VALUES('VOLTE',3)
INSERT INTO LOOKUPVALUE VALUES('WIFI',3)
INSERT INTO LOOKUPVALUE VALUES('LAN',3)

INSERT INTO LOOKUPVALUE VALUES('MOBILENO',4)
INSERT INTO LOOKUPVALUE VALUES('GMAIL',4)
INSERT INTO LOOKUPVALUE VALUES('EMAIL&PASSWORD',4)



SELECT * FROM LOOKUPVALUE




CREATE TABLE USERDEVICEMAPPING([USERDEVICEMAPPINGID] INT IDENTITY(1,1),[USERID] INT,[LOOKUPVALUEID] INT)
INSERT INTO USERDEVICEMAPPING VALUES(1,4)
INSERT INTO USERDEVICEMAPPING VALUES(2,4)
INSERT INTO USERDEVICEMAPPING VALUES(1,5)
INSERT INTO USERDEVICEMAPPING VALUES(2,5)
INSERT INTO USERDEVICEMAPPING VALUES(3,4)
INSERT INTO USERDEVICEMAPPING VALUES(4,5)
INSERT INTO USERDEVICEMAPPING VALUES(5,5)
INSERT INTO USERDEVICEMAPPING VALUES(6,4)
SELECT * FROM USERDEVICEMAPPING

CREATE TABLE FACEBOOKHISTORY([FHISTORY] INT IDENTITY(1,1) ,[USERDEVICEMAPPINGID] INT ,
[LOOKUPVALUEIDCONNECTION] INT,[LOOKUPVALUEIDHITTYPE] INT,[USERID] INT,[CREATEDON] DATETIME DEFAULT GETDATE())

INSERT INTO FACEBOOKHISTORY VALUES(1,7,2,1,GETDATE())
INSERT INTO FACEBOOKHISTORY VALUES(2,8,3,2,GETDATE())
INSERT INTO FACEBOOKHISTORY VALUES(3,7,2,1,GETDATE())
INSERT INTO FACEBOOKHISTORY VALUES(1,7,2,1,GETDATE())
INSERT INTO FACEBOOKHISTORY VALUES(1,7,2,1,GETDATE())


INSERT INTO FACEBOOKHISTORY VALUES(1,7,2,1,GETDATE())
INSERT INTO FACEBOOKHISTORY VALUES(1,7,2,1,GETDATE())
INSERT INTO FACEBOOKHISTORY VALUES(2,8,3,2,GETDATE())
INSERT INTO FACEBOOKHISTORY VALUES(3,7,2,1,GETDATE())
INSERT INTO FACEBOOKHISTORY VALUES(1,7,2,1,GETDATE())


ALTER TABLE FACEBOOKHISTORY ADD USERID INT
UPDATE FACEBOOKHISTORY SET USERID=6 WHERE FHISTORY>15 AND FHISTORY<=16

SELECT * FROM FACEBOOKHISTORY

SELECT * FROM USERDEVICEMAPPING
SELECT * FROM LOOKUPVALUE
--SELECT * FROM LOOKUPTYPE
SELECT * FROM USER_DATA

SELECT COUNT(*) AS TotalHitsByLaptop
FROM FACEBOOKHISTORY FH
JOIN USERDEVICEMAPPING UDM ON FH.USERDEVICEMAPPINGID = UDM.USERDEVICEMAPPINGID
JOIN LOOKUPVALUE LV ON UDM.LOOKUPVALUEID = LV.LOOKUPVALUEID
JOIN LOOKUPVALUE LV_Device ON FH.LOOKUPVALUEIDCONNECTION = LV_Device.LOOKUPVALUEID
WHERE LV_Device.LOOKUPVALUENAME = 'LAPTOP';


SELECT COUNT(*) AS TotalHitsByLaptop
FROM FACEBOOKHISTORY FH
JOIN USERDEVICEMAPPING UDM ON FH.USERDEVICEMAPPINGID = UDM.USERDEVICEMAPPINGID
JOIN LOOKUPVALUE LV ON UDM.LOOKUPVALUEID = LV.LOOKUPVALUEID
JOIN LOOKUPVALUE LV_Device ON FH.LOOKUPVALUEIDCONNECTION = LV_Device.LOOKUPVALUEID
WHERE LV_Device.LOOKUPVALUENAME = 'LAPTOP';


SELECT LV_Connection.LOOKUPVALUENAME AS ConnectionType, LV_Device.LOOKUPVALUENAME AS DeviceType, COUNT(*) AS TotalHits
FROM FACEBOOKHISTORY FH
JOIN USERDEVICEMAPPING UDM ON FH.USERDEVICEMAPPINGID = UDM.USERDEVICEMAPPINGID
JOIN LOOKUPVALUE LV_Connection ON FH.LOOKUPVALUEIDCONNECTION = LV_Connection.LOOKUPVALUEID
JOIN LOOKUPVALUE LV_Device ON UDM.LOOKUPVALUEID = LV_Device.LOOKUPVALUEID
GROUP BY LV_Connection.LOOKUPVALUENAME, LV_Device.LOOKUPVALUENAME;

SELECT * FROM USER_DATA  UD LEFT OUTER JOIN USERDEVICEMAPPING  DM ON  UD.USERID=DM.USERID



SELECT COUNT(DM.LOOKUPVALUEID ) TOTAL ,UD.USEREMAIL,UD.USERNAME FROM USER_DATA  UD LEFT OUTER JOIN USERDEVICEMAPPING  DM ON  UD.USERID=DM.USERID
GROUP BY UD.USEREMAIL,UD.USERNAME

ORDER BY UD.USERNAME DESC


SELECT * FROM USER_DATA  UD  JOIN USERDEVICEMAPPING  DM ON UD.USERID=DM.USERID

SELECT * FROM LOOKUPTYPE LT JOIN LOOKUPVALUE LV ON LT.LOOKUPTYPEID=LV.LOOKUPTYPEID 
JOIN USERDEVICEMAPPING DM ON DM.LOOKUPVALUEID=LT.LOOKUPTYPEID 
JOIN USER_DATA UD ON DM.USERID=UD.USERID 
JOIN FACEBOOKHISTORY FB ON FB.USERID=UD.USERID

SELECT * FROM FACEBOOKHISTORY

--total hit by connection with device type


UPDATE FACEBOOKHISTORY SET USERID = 10 
sp_rename 'FACEBOOKHISTORY.USERID', 'LOOKUPVALUEAUTHENTICATION', 'COLUMN';


SELECT COUNT(LV.LOOKUPVALUENAME) FROM FACEBOOKHISTORY FB JOIN USERDEVICEMAPPING DM ON FB.USERDEVICEMAPPINGID=DM.USERDEVICEMAPPINGID
JOIN LOOKUPVALUE LV ON LV.LOOKUPVALUEID=DM.LOOKUPVALUEID WHERE LV.LOOKUPVALUENAME='LAPTOP'

-- max hit by user
SELECT * FROM USERDEVICEMAPPING DM JOIN LOOKUPVALUE LV ON DM.LOOKUPVALUEID=LV.LOOKUPVALUEID 
JOIN USER_DATA UD ON UD.USERID=DM.USERID JOIN FACEBOOKHISTORY FB ON FB.USERDEVICEMAPPINGID=DM.USERDEVICEMAPPINGID 

SELECT  COUNT(UD.USERNAME) TOTAL,UD.USERNAME FROM  USER_DATA UD JOIN USERDEVICEMAPPING DM ON UD.USERID=DM.USERID 
JOIN FACEBOOKHISTORY FB ON FB.USERDEVICEMAPPINGID=DM.USERDEVICEMAPPINGID
JOIN LOOKUPVALUE LV ON LV.LOOKUPVALUEID=FB.LOOKUPVALUEIDHITTYPE
GROUP BY UD.USERNAME
ORDER BY TOTAL DESC

--INSERT THE DATA FROM ONE TABLE TO ANOTHER TABLE
INSERT INTO USERDEVICEMAPPING
SELECT USERID,4 FROM USER_DATA

INSERT INTO FACEBOOKHISTORY 
SELECT USERDEVICEMAPPINGID,8,1,11,GETDATE() FROM USERDEVICEMAPPING DM JOIN LOOKUPVALUE LV ON DM.LOOKUPVALUEID=LV.LOOKUPVALUEID 



--SELECT * FROM FACEBOOKHISTORY 

--Query 1:total hit by laptop   : TABLE USE LOOKUPVALUE,FACEBOOKHISTORY,USERDEVICEMAPPING

SELECT * FROM USERDEVICEMAPPING DM 
INNER JOIN LOOKUPVALUE LV ON DM.LOOKUPVALUEID=LV.LOOKUPVALUEID 
INNER JOIN FACEBOOKHISTORY FB ON FB.LOOKUPVALUEIDHITTYPE=LV.LOOKUPVALUEID

SELECT COUNT(LV.LOOKUPVALUEID) TOTAL ,LV.LOOKUPVALUENAME  FROM FACEBOOKHISTORY FB 
INNER JOIN USERDEVICEMAPPING DM ON FB.USERDEVICEMAPPINGID=DM.USERDEVICEMAPPINGID
INNER JOIN LOOKUPVALUE LV ON LV.LOOKUPVALUEID=DM.LOOKUPVALUEID
WHERE LV.LOOKUPVALUEID=5
GROUP BY LV.LOOKUPVALUENAME



--Query 2: max hit by user    : TABLE USE: USERDATA,USERDEVICEMAPPING ,LOOKUPVALUE
SELECT COUNT(*)TOTALHITS,UD.USERNAME  FROM USER_DATA UD 
JOIN USERDEVICEMAPPING DM ON UD.USERID=DM.USERID
--JOIN LOOKUPVALUE LV ON LV.LOOKUPVALUEID = DM.LOOKUPVALUEID
JOIN FACEBOOKHISTORY FB ON FB.USERDEVICEMAPPINGID=DM.USERDEVICEMAPPINGID
GROUP BY UD.USERNAME
ORDER BY TOTALHITS DESC





SELECT  COUNT(UD.USERNAME) TOTAL,UD.USERNAME FROM  USER_DATA UD
JOIN USERDEVICEMAPPING DM ON UD.USERID=DM.USERID 
JOIN FACEBOOKHISTORY FB ON FB.USERDEVICEMAPPINGID=DM.USERDEVICEMAPPINGID
JOIN LOOKUPVALUE LV ON LV.LOOKUPVALUEID=FB.LOOKUPVALUEIDHITTYPE
GROUP BY UD.USERNAME
ORDER BY TOTAL DESC

--AMAN
SELECT COUNT(*) TOTAL,UD.USERNAME  FROM FACEBOOKHISTORY FB 
JOIN USERDEVICEMAPPING DM ON FB.USERDEVICEMAPPINGID=DM.USERDEVICEMAPPINGID
JOIN USER_DATA UD ON UD.USERID=DM.USERID
--JOIN LOOKUPVALUE LV ON LV.LOOKUPTYPEID =DM.LOOKUPVALUEID
GROUP BY UD.USERNAME 


--DHRITI
select u.U_name,COUNT(*) as MaxHitByUser from FACEBOOKHISTORY h
join USERDEVICEMAPPING um on h.USERDEVICEMAPPINGID=um.USERDEVICEMAPPINGID
join USER_DATA u on u.USERID=um.USERID
join LOOKUPVALUE lvauth on h.authentication_type=lvauth.lookup_val_id
group by u.U_name,lvauth.lookup_value

SELECT COUNT(FB.LOOKUPVALUEIDHITTYPE)TOTAL,UD.USERNAME FROM FACEBOOKHISTORY FB JOIN USER_DATA UD ON FB.USERID=UD.USERID W
GROUP BY UD.USERNAME

--total type device

SELECT * FROM LOOKUPVALUE WHERE LOOKUPTYPEID=2 

-- total type of network
SELECT * FROM LOOKUPVALUE WHERE LOOKUPTYPEID=3


--total hit by connection with device type  :: FACEBOOK , LOOK UP VALUE,DEVICE MAPPING
SELECT COUNT(*),LV.LOOKUPVALUENAME,LVH.LOOKUPVALUENAME FROM FACEBOOKHISTORY FB 
JOIN LOOKUPVALUE LV ON FB.LOOKUPVALUEIDCONNECTION = LV.LOOKUPVALUEID
JOIN LOOKUPVALUE LVH ON FB.LOOKUPVALUEIDHITTYPE=LVH.LOOKUPVALUEID
JOIN USERDEVICEMAPPING DM ON FB.USERDEVICEMAPPINGID =DM.USERDEVICEMAPPINGID
GROUP BY LV.LOOKUPVALUENAME,LVH.LOOKUPVALUENAME

--hit type with date range
SELECT LV.LOOKUPVALUEID FROM FACEBOOKHISTORY FB 
JOIN LOOKUPVALUE LV ON FB.LOOKUPVALUEIDHITTYPE=LV.LOOKUPVALUEID
WHERE LV.LOOKUPTYPEID<=3 AND FB.CREATEDON BETWEEN '2023-08-10 14:47:43.950' AND '2023-08-10 17:47:43.950'


--LAST MODIFIED DATE
SELECT TOP 1 CREATEDON FROM FACEBOOKHISTORY ORDER BY CREATEDON DESC

 




